version: '3'

services:
  frontend:
    build: ./frontend
    ports:
    - "8089:80"

  db:
    build: ./database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3990:3990"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:pwd@db:5432/db"
      BACKEND_PORT: "3990"
