######################################################################
# Automatically generated by qmake (3.0) Sat Dec 25 12:38:09 2021
######################################################################

TEMPLATE = app
TARGET = qpushbutton_example_mingw-w64
INCLUDEPATH += .

# Input
SOURCES += main.cpp
