######################################################################
# Automatically generated by qmake (3.0) Wed Dec 23 10:16:24 2020
######################################################################

TEMPLATE = app
TARGET = mingw64_qt_gui
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets 
