keywords = [
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "neural network",
    "transformer model",
    "large language model",
    "computer vision",
    "natural language processing",
    "robotics",
    "automation",
    "algorithm",
    "data structure",
    "database",
    "distributed system",
    "operating system",
    "compiler",
    "programming language",
    "python",
    "javascript",
    "linux",
    "kernel",
    "web server",
    "api",
    "cloud computing",
    "docker",
    "kubernetes",
    "microservice",
    "blockchain",
    "cryptocurrency",
    "bitcoin",
    "ethereum",
    "cybersecurity",
    "encryption",
    "cryptography",
    "hash function",
    "network protocol",
    "tcp",
    "udp",
    "http",
    "internet",
    "browser",
    "search engine",
    "social media",
    "quantum computing",
    "quantum mechanics",
    "relativity",
    "gravity",
    "black hole",
    "dark matter",
    "dark energy",
    "galaxy",
    "nebula",
    "supernova",
    "planet",
    "star",
    "moon",
    "asteroid",
    "comet",
    "solar system",
    "universe",
    "cosmology",
    "space exploration",
    "satellite",
    "rocket",
    "spacecraft",
    "mars",
    "jupiter",
    "earth",
    "atmosphere",
    "climate",
    "weather",
    "storm",
    "hurricane",
    "tornado",
    "rainfall",
    "lightning",
    "volcano",
    "earthquake",
    "tectonic plate",
    "ocean",
    "river",
    "lake",
    "mountain",
    "desert",
    "forest",
    "ecosystem",
    "biodiversity",
    "evolution",
    "natural selection",
    "species",
    "animal",
    "mammal",
    "bird",
    "reptile",
    "fish",
    "insect",
    "fungus",
    "bacteria",
    "virus",
    "cell",
    "dna",
    "rna",
    "protein",
    "enzyme",
    "genetics",
    "biology",
    "microbiology",
    "ecology",
    "photosynthesis",
    "metabolism",
    "immune system",
    "human brain",
    "neuron",
    "consciousness",
    "memory",
    "psychology",
    "behavior",
    "emotion",
    "language",
    "philosophy",
    "logic",
    "ethics",
    "metaphysics",
    "epistemology",
    "mathematics",
    "algebra",
    "geometry",
    "calculus",
    "statistics",
    "probability",
    "number theory",
    "topology",
    "linear algebra",
    "equation",
    "function",
    "vector",
    "matrix",
    "physics",
    "chemistry",
    "atom",
    "molecule",
    "electron",
    "proton",
    "neutron",
    "periodic table",
    "chemical reaction",
    "acid",
    "base",
    "polymer",
    "material science",
    "steel",
    "plastic",
    "glass",
    "semiconductor",
    "battery",
    "electricity",
    "magnetism",
    "voltage",
    "current",
    "resistance",
    "energy",
    "power",
    "solar power",
    "wind energy",
    "nuclear energy",
    "hydroelectricity",
    "engineering",
    "civil engineering",
    "mechanical engineering",
    "electrical engineering",
    "aerospace engineering",
    "bridge",
    "tunnel",
    "airplane",
    "helicopter",
    "train",
    "automobile",
    "electric vehicle",
    "engine",
    "fuel",
    "manufacturing",
    "factory",
    "supply chain",
    "economics",
    "inflation",
    "recession",
    "currency",
    "bank",
    "stock market",
    "investment",
    "finance",
    "trade",
    "capitalism",
    "socialism",
    "market economy",
    "globalization",
    "business",
    "startup",
    "entrepreneurship",
    "leadership",
    "management",
    "marketing",
    "advertising",
    "branding",
    "education",
    "school",
    "university",
    "learning",
    "teaching",
    "history",
    "archaeology",
    "civilization",
    "ancient rome",
    "ancient egypt",
    "greek mythology",
    "renaissance",
    "industrial revolution",
    "world war i",
    "world war ii",
    "cold war",
    "democracy",
    "government",
    "politics",
    "law",
    "justice",
    "constitution",
    "society",
    "culture",
    "religion",
    "mythology",
    "literature",
    "poetry",
    "novel",
    "storytelling",
    "music",
    "art",
    "painting",
    "sculpture",
    "architecture",
    "design",
    "photography",
    "cinema",
    "film",
    "television",
    "video game",
    "virtual reality",
    "augmented reality",
    "sports",
    "football",
    "basketball",
    "cricket",
    "tennis",
    "olympics",
    "health",
    "medicine",
    "disease",
    "vaccine",
    "surgery",
    "nutrition",
    "exercise",
    "sleep",
    "diet",
    "public health",
    "agriculture",
    "farming",
    "food",
    "cooking",
    "nutrition science",
    "coffee",
    "tea",
    "bread",
    "rice",
    "urban planning",
    "city",
    "transportation",
    "infrastructure",
    "architecture history",
    "renewable energy",
    "sustainability",
    "pollution",
    "recycling",
    "waste management",
    "water treatment",
    "mining",
    "geology",
    "mineral",
    "metal",
    "gold",
    "iron",
    "silicon",
    "rare earth elements",
    "nanotechnology",
    "biotechnology",
    "gene editing",
    "crispr",
    "bioinformatics",
    "astronomy",
    "astrophysics",
    "linguistics",
    "anthropology",
    "sociology",
    "game theory",
    "decision theory",
    "information theory",
    "signal processing",
    "control systems",
    "embedded systems",
    "computer graphics",
    "animation",
    "data science",
    "big data",
    "visualization",
    "reinforcement learning",
    "supervised learning",
    "unsupervised learning",
    "recommendation system",
    "search ranking",
    "human computer interaction",
    "user interface",
    "user experience",
    "open source software",
    "software engineering",
    "testing",
    "debugging",
    "version control",
    "git",
    "compiler optimization",
    "memory management",
    "file system",
    "parallel computing",
    "gpu",
    "cpu",
    "microprocessor",
    "transistor",
    "electronics",
]

import random
import llm

def get_templates():
    # 59 keywords
    selected_keywords = keywords[:59]
    # 3 prompt structures
    structures = [
        "Tell me what do you think about {topic} in a format starting with 'I ____' like this: 'I think ____', 'I am _____', 'I feel _____', 'I did ______', etc"
        "Write an essay about {topic} in a {tone} tone.",
        "Provide a comprehensive overview of {topic} in a {tone} tone.",
        "Create a detailed discussion regarding {topic} in a {tone} tone."
    ]
    # 4 tones
    tones = [
        "formal and academic",
        "casual and friendly",
        "concise and technical",
        "creative and storytelling"
    ]
    
    templates = []
    for structure in structures:
        for tone in tones:
            for keyword in selected_keywords:
                templates.append(structure.format(topic=keyword, tone=tone))
    return templates

def generate_synthetic_data_batch(batch_size: int, output_file: str = "dataset-ex226.txt") -> list:
    templates = get_templates()
    assert len(templates) == 708, f"Expected 708 templates, got {len(templates)}"
    
    chosen_prompts = random.choices(templates, k=batch_size)
    generated_texts = []
    
    for i, prompt in enumerate(chosen_prompts):
        print(f"Generating batch item {i+1}/{batch_size} using template: {prompt}")
        try:
            res = llm.invoke(prompt)
            if res:
                generated_texts.append(res)
                with open(output_file, "a", encoding="utf-8") as f:
                    f.write(res + "\n")
        except Exception as e:
            print(f"Error invoking LLM: {e}")
            
    return generated_texts

if __name__ == "__main__":
    # Test generation of a small batch of 2
    print("Testing prompt generation...")
    templates = get_templates()
    print(f"Total prompt templates generated: {len(templates)}")
    print("Generating a small batch of 2 synthetic data samples...")
    batch = generate_synthetic_data_batch(2)
    print(f"Generated {len(batch)} samples.")