#!/bin/bash
engine="podman" # or "docker"

function exe(){
	echo "$1";
	$1;
}

exe "$engine --version"

if [ "$engine" = "podman" ]; then
	podman_is_running=$(ps -ef | grep -i podman | grep -i gvproxy)
	if [ "$podman_is_running" = "" ]; then
		exe "podman machine start"
	fi
fi


if [ "$1" = "" ]; then
	container_name="ubuntu1"
else
	container_name="$1"
fi

exe "$engine run --name $container_name -it -d -p 5000:5000 ubuntu bash"

exe "$engine exec -it $container_name bash"

