#!/bin/bash
if [ ! -d venv ]; then 
	fn="lambda"
	if [ "$1" != "" ]; then
		fn="$1"
	fi
	mkdir $fn
	cd $fn

	virtualenv venv --python=python3
	pwd
fi


source venv/bin/activate
pip3 install flask flask_cors
pip3 freeze > requirements.txt

touch app.py
printf "import flask\nimport flask_cors\n\n\napp = flask.Flask(__name__)\nflask_cors.CORS(app)\n\n" >> app.py
printf "venv/\n__pycache__/\nnode_modules/\n" >> .gitignore
