#!/bin/bash
#engine="podman"
engine="docker"
distroname=fedora
function exe(){
	echo "$1";
	$1;
}

exe "$engine --version"

if [ "$engine" = "podman" ]; then
	podman_is_running=$(ps -ef | grep -i podman | grep -i gvproxy)
	if [ "$podman_is_running" = "" ]; then
		exe "podman machine start"
	fi
fi


if [ "$1" = "" ]; then
	container_name="${distroname}1"
else
	container_name="$1"
fi


echo container name is $container_name
container_exists="$($engine ps -a | grep $container_name)"

if [ "$container_exists" = "" ]; then
	echo creating container..
	exe "$engine run --name $container_name -it -d -p 5000:5000 ${distroname} bash"
fi

exe "$engine start $container_name"

exe "$engine ps -a"
