#!/bin/bash
engine="podman" # or "docker"
platform=$(uname -s)

function exe(){
	echo "$1";
	$1;
}

exe "$engine --version"

if [ "$engine" = "podman" ]; then
	if [ "$platform" = "Darwin" ]; then
		podman_is_running=$(ps -ef | grep -i podman | grep -i gvproxy)
	else
		podman_is_running=$(ps -ef | grep -i podman | grep -i qemu)
	fi

	if [ "$podman_is_running" = "" ]; then
		exe "podman machine start"
	fi
fi


if [ "$1" = "" ]; then
	container_name="ubuntu1"
else
	container_name="$1"
fi

container_exists="$(podman ps -a | grep $container_name)"

if [ "$container_exists" = "" ]; then
	exe "$engine run --name $container_name -it -d -p 5000:5000 ubuntu bash"
else
	exe "$engine start $container_name"
fi

exe "$engine exec -it $container_name bash"	


