#!/bin/bash
exe(){
	echo "$1";
	$1;
}

exe "podman stop $(podman ps -aq)"

if [ "$1" = "-a" ]; then
	exe "podman rm $(podman ps -aq)"
	exe "podman machine stop"
fi

if [ "$1" = "-k" ]; then
	exe "podman machine stop"
	exe "pkill gvproxy qemu-system-aarch64"
fi

