#!/bin/bash
a=( node_modules __pycache__ venv );
b=$(echo ${#a[@]})

c="0"

if [ -r .gitignore ]; then
	echo found .gitignore;
else
	echo creating .gitignore;
	touch .gitignore;
fi

while [ $c -lt $b ]; do
	tgt=$(echo ${a[$c]}/)
	if [[ -d $target && $(grep $target .gitignore) = "" ]]; then
		echo $target >> .gitignore
		echo adding $target to .gitignore...
	fi
	c=$(expr $c "+" 1);
done

if [[ -r .env && ! $(grep -q .env .gitignore) ]] ; then
    echo .env >> .gitignore
fi
