######################################################################
# Automatically generated by qmake (3.0) Sat Dec 25 12:34:44 2021
######################################################################

TEMPLATE = app
TARGET = winbuilds-qmake-mingw-w64-windows
INCLUDEPATH += .

# Input
SOURCES += main.cpp
