version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: d2user
      POSTGRES_PASSWORD: d2pwd
      POSTGRES_DB: d2db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://d2user:d2pwd@db:5432/d2db"
